server:
  port: 8888
spring:
  application:
    name: greeting-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/julianocls/greeting-config-server-repo
          #username:
          #password:
          default-label: main
          search-paths:
          - 'greeting-service*'



